defmodule Vite.View do
  @moduledoc """
  Help with View integration into Phoenix views
  """

  alias Vite.{Config, ManifestReader}

  @doc """
  Helper to generate inlined Phoenix cache manifest to simplify integration with Javascript code.

  The manifest generated by `mix phx.digest` is stored in a global variable `window.PhxManifest`.
  Only works in :prod environment.
  """
  @spec inlined_phx_manifest() :: {atom(), binary()} | binary()
  def inlined_phx_manifest do
    if Vite.production?() do
      manifest =
        ManifestReader.read_phx()
        |> Map.get("latest")
        |> Config.json_library().encode!(pretty: true)

      as_safe(["<script>window.PhxManifest = ", [manifest, ["</script>"]]])
    else
      ""
    end
  end

  defp as_safe(s), do: {:safe, s}
end
